"""edit model model user

Revision ID: b4866b331c2f
Revises: f23281c76f46
Create Date: 2026-01-26 16:44:54.409234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4866b331c2f'
down_revision = 'f23281c76f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.Enum('admin', 'user'), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
