"""init tables

Revision ID: b97f493cf94b
Revises: 
Create Date: 2026-01-26 15:15:04.977797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97f493cf94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('read_page', sa.Integer(), nullable=True),
    sa.Column('reading', sa.Boolean(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('publisher', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('page_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_page', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reading', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('inserted_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('books')
    # ### end Alembic commands ###
